config/routes.rb
Cheval::Application.routes.draw do
  resources :twitter_tags


  resources :food_sliders


devise_for :admins, :controllers => {:registrations => "registrations"}, :skip => [:registrations]
as :admin do
  get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
  put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
end

  match "/about" => "static#about", as: :about
  match "/menu" => "static#menu", as: :menu
  match "/photos" => "static#photos", as: :photos
  match "/art_club" => "static#art_club", as: :art_club
  match "/press" => "static#press", as: :press
  match "/contact" => "static#contact", as: :contact
  match "/upcoming_events" => "static#upcoming_events", as: :upcoming_events
  match "/past_events" => "static#past_events", as: :past_events
  match "/show_event/:id" => "static#show_event", as: :show_event

  scope "/admin" do
    root to: "events#index"
    resources :events
    resources :slider_images  
    resources :special_menus
    resources :press_links
    resources :print_media
  end

  root to: "static#index"
end

app/models/special_menu.rb
class SpecialMenu < ActiveRecord::Base
  attr_accessible :description, :name, :menu_images_attributes, :hidden, :thumbnail_image
  has_many :menu_images
  has_attached_file :thumbnail_image, :styles => { :cropped => "270x270!" }, :default_url => "/assets/missing.png"
  accepts_nested_attributes_for :menu_images, :allow_destroy => true
  default_scope where("hidden = false").order("created_at DESC")
end

app/controllers/special_menus_controller.rb
class SpecialMenusController < ApplicationController
  layout 'admin'

  # GET /special_menus
  # GET /special_menus.json
  def index
    @special_menus = SpecialMenu.unscoped.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @special_menus }
    end
  end

  # GET /special_menus/1
  # GET /special_menus/1.json
  def show
    @special_menu = SpecialMenu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @special_menu }
    end
  end

  # GET /special_menus/new
  # GET /special_menus/new.json
  def new
    @special_menu = SpecialMenu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @special_menu }
    end
  end

  # GET /special_menus/1/edit
  def edit
    @special_menu = SpecialMenu.unscoped.find(params[:id])
  end

  # POST /special_menus
  # POST /special_menus.json
  def create
    @special_menu = SpecialMenu.new(params[:special_menu])

    respond_to do |format|
      if @special_menu.save
        format.html { 
          gflash success: 'Special menu was successfully created.' 
          redirect_to special_menus_path
        }
        format.json { render json: @special_menu, status: :created, location: @special_menu }
      else
        format.html { render action: "new" }
        format.json { render json: @special_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /special_menus/1
  # PUT /special_menus/1.json
  def update
    @special_menu = SpecialMenu.unscoped.find(params[:id])

    respond_to do |format|
      if @special_menu.update_attributes(params[:special_menu])
        format.html { 
          gflash success: 'Special menu was successfully updated.'
          redirect_to special_menus_path
        }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @special_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /special_menus/1
  # DELETE /special_menus/1.json
  def destroy
    @special_menu = SpecialMenu.unscoped.find(params[:id])
    @special_menu.destroy

    respond_to do |format|
      format.html { redirect_to special_menus_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/special_menus_helper.rb
module SpecialMenusHelper
end

app/views/special_menus/_form.html.erb
<%= nested_form_for @special_menu, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <div class="span8">
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :thumbnail_image, "#{@special_menu.persisted? ? 'Change menu thmbnail' : 'Menu thmbnail' }", :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :thumbnail_image, :class => 'text_field' %>
      </div>
    </div>  
    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :class => '', :size => "50x5", :style => "width:auto" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :hidden, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :hidden, :class => 'check_box' %>
      </div>
    </div>
  </div>
  <div class="san3">
    <% unless @special_menu.thumbnail_image.blank? %>
      Special menu thumbnail<br>
      <%= image_tag @special_menu.thumbnail_image.url(:cropped), :width => 200 %>
    <% end %>
  </div>
  <div class="clearfix"></div>
  <%= f.fields_for :menu_images do |menu_image_form| %>
    <div class="clearfix">
      <h4>Menu page</h4>
      <hr>
      <div class="pull-left">
        <div class="control-group">
          <%= menu_image_form.label :image, menu_image_form.object.persisted? ? "Change image" : "Page image", :class => 'control-label' %>
          <div class="controls">      
            <%= menu_image_form.file_field :image, :class => 'file_field' %>
          </div>
        </div>
        <div class="control-group">
          <%= menu_image_form.label :page_number, :class => 'control-label' %>
          <div class="controls">      
            <%= menu_image_form.number_field :page_number, :class => 'text_field' %>
          </div>
        </div>
        <div class="control-group">
          <span style="padding-left:75px"></span><%= menu_image_form.link_to_remove "Remove this menu page" %>
        </div>
      </div>
      <div class="pull-left" style="padding-left: 50px">
        <% if menu_image_form.object.persisted? %>
          <%= link_to image_tag(menu_image_form.object.image.url(:thumb)), menu_image_form.object.image.url(:cropped), :target => "_blank" %>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= f.link_to_add "Add a menu page", :menu_images%>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-success' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), special_menus_path, :class => 'btn' %>
  </div>
<% end %>

app/views/special_menus/edit.html.erb
<%- model_class = SpecialMenu -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/special_menus/index.html.erb
<%- model_class = SpecialMenu -%>
<div class="page-header">
  <h1>
    <%=t '.title', :default => model_class.model_name.human.pluralize %>
    <%= link_to new_special_menu_path, :class => 'btn btn-success pull-right' do %>
      <i class='icon-plus icon-white'></i> Add Special Menu
    <% end %>
  </h1>
</div>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:hidden) %></th>
      <th>No of pages</th>
      <th>Created on</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @special_menus.each do |special_menu| %>
      <tr>
        <td><%= special_menu.name %></td>
        <td><%= special_menu.hidden ? "Yes" : "No" %></td>
        <td><%= special_menu.menu_images.count %></td>
        <td><%= special_menu.created_at.strftime("%d %B, %Y") %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_special_menu_path(special_menu), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      special_menu_path(special_menu),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/special_menus/new.html.erb
<%- model_class = SpecialMenu -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/special_menus/show.html.erb
<%- model_class = SpecialMenu -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @special_menu.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @special_menu.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hidden) %>:</strong></dt>
  <dd><%= @special_menu.hidden %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              special_menus_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_special_menu_path(@special_menu), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              special_menu_path(@special_menu),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>