config/routes.rb
Cheval::Application.routes.draw do
  resources :twitter_tags


  resources :food_sliders


devise_for :admins, :controllers => {:registrations => "registrations"}, :skip => [:registrations]
as :admin do
  get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
  put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
end

  match "/about" => "static#about", as: :about
  match "/menu" => "static#menu", as: :menu
  match "/photos" => "static#photos", as: :photos
  match "/art_club" => "static#art_club", as: :art_club
  match "/press" => "static#press", as: :press
  match "/contact" => "static#contact", as: :contact
  match "/upcoming_events" => "static#upcoming_events", as: :upcoming_events
  match "/past_events" => "static#past_events", as: :past_events
  match "/show_event/:id" => "static#show_event", as: :show_event

  scope "/admin" do
    root to: "events#index"
    resources :events
    resources :slider_images  
    resources :special_menus
    resources :press_links
    resources :print_media
  end

  root to: "static#index"
end

app/models/food_slider.rb
class FoodSlider < ActiveRecord::Base
  attr_accessible :hidden, :image
  has_attached_file :image, :styles => { :thumb => "300x100!", :cropped => "1200x500#" }, :default_url => "/images/:style/missing.png"
end

app/controllers/food_sliders_controller.rb
class FoodSlidersController < ApplicationController
  before_filter :authenticate_admin!
  layout "admin"
  # GET /food_sliders
  # GET /food_sliders.json
  def index
    @food_sliders = FoodSlider.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @food_sliders }
    end
  end

  # GET /food_sliders/1
  # GET /food_sliders/1.json
  def show
    @food_slider = FoodSlider.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @food_slider }
    end
  end

  # GET /food_sliders/new
  # GET /food_sliders/new.json
  def new
    @food_slider = FoodSlider.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @food_slider }
    end
  end

  # GET /food_sliders/1/edit
  def edit
    @food_slider = FoodSlider.find(params[:id])
  end

  # POST /food_sliders
  # POST /food_sliders.json
  def create
    @food_slider = FoodSlider.new(params[:food_slider])

    respond_to do |format|
      if @food_slider.save
        format.html { redirect_to food_sliders_url, notice: 'Food slider was successfully created.' }
        format.json { render json: @food_slider, status: :created, location: @food_slider }
      else
        format.html { render action: "new" }
        format.json { render json: @food_slider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /food_sliders/1
  # PUT /food_sliders/1.json
  def update
    @food_slider = FoodSlider.find(params[:id])

    respond_to do |format|
      if @food_slider.update_attributes(params[:food_slider])
        format.html { redirect_to food_sliders_url, notice: 'Food slider was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @food_slider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_sliders/1
  # DELETE /food_sliders/1.json
  def destroy
    @food_slider = FoodSlider.find(params[:id])
    @food_slider.destroy

    respond_to do |format|
      format.html { redirect_to food_sliders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/food_sliders_helper.rb
module FoodSlidersHelper
end

app/views/food_sliders/_form.html.erb
<%= form_for @food_slider, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="clearfix">
    <div class="pull-left">
      <div class="control-group">
        <%= f.label :hidden, :class => 'control-label' %>
        <div class="controls">
          <%= f.check_box :hidden, :class => 'check_box' %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :image, "#{@food_slider.persisted? ? 'Change Image' : 'Image' }", :class => 'control-label' %>
        <div class="controls">
          <%= f.file_field :image, :class => 'file_field' %>
        </div>
      </div>
    </div>
    <div class="pull-left">
      <%= image_tag @food_slider.image.url(:thumb) if @food_slider.persisted? %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-success' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                food_sliders_path, :class => 'btn' %>
  </div>
<% end %>

app/views/food_sliders/edit.html.erb
<%- model_class = SliderImage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/food_sliders/index.html.erb
<%- model_class = SliderImage -%>
<div class="page-header">
  <h1>
    Food & Bar Slider
    <%= link_to new_food_slider_path, :class => 'btn btn-success pull-right' do %>
      <i class='icon-plus icon-white'></i> Add Slider Image
    <% end %>
  </h1>
</div>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:hidden) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @food_sliders.each do |food_slider| %>
      <tr>
        <td><%= image_tag food_slider.image.url(:thumb) %></td>
        <td><%= food_slider.hidden ? "Yes" : "No" %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_food_slider_path(food_slider), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      food_slider_path(food_slider),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/food_sliders/new.html.erb
<%- model_class = SliderImage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/food_sliders/show.html.erb
<%- model_class = SliderImage -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:hidden) %>:</strong></dt>
  <dd><%= @food_slider.hidden %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image_file_name) %>:</strong></dt>
  <dd><%= @food_slider.image_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image_content_type) %>:</strong></dt>
  <dd><%= @food_slider.image_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image_file_size) %>:</strong></dt>
  <dd><%= @food_slider.image_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image_updated_at) %>:</strong></dt>
  <dd><%= @food_slider.image_updated_at %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              food_sliders_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_food_slider_path(@food_slider), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              food_slider_path(@food_slider),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>