config/routes.rb
Cheval::Application.routes.draw do
  resources :twitter_tags


  resources :food_sliders


devise_for :admins, :controllers => {:registrations => "registrations"}, :skip => [:registrations]
as :admin do
  get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
  put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
end

  match "/about" => "static#about", as: :about
  match "/menu" => "static#menu", as: :menu
  match "/photos" => "static#photos", as: :photos
  match "/art_club" => "static#art_club", as: :art_club
  match "/press" => "static#press", as: :press
  match "/contact" => "static#contact", as: :contact
  match "/upcoming_events" => "static#upcoming_events", as: :upcoming_events
  match "/past_events" => "static#past_events", as: :past_events
  match "/show_event/:id" => "static#show_event", as: :show_event

  scope "/admin" do
    root to: "events#index"
    resources :events
    resources :slider_images  
    resources :special_menus
    resources :press_links
    resources :print_media
  end

  root to: "static#index"
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_pictures
  attr_accessible :description, :done, :name, :scheduled_on, :poster, :event_pictures_attributes, :thumbnail_poster, :youtube_url
  has_attached_file :poster, :default_url => "/assets/missing.png"
  has_attached_file :thumbnail_poster, :styles => { :cropped => "270x270!" }, :default_url => "/assets/missing.png"
  # default_scope order("created_at DESC")
  scope :upcoming, lambda { where("scheduled_on >= ?", (Date.today-1.days)).order("scheduled_on ASC") }
  scope :past, lambda { where("scheduled_on < ?", (Date.today-1.days)).order("scheduled_on DESC") }
  validates_presence_of :name, :scheduled_on, :poster, :description
  accepts_nested_attributes_for :event_pictures, :allow_destroy => true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_admin!
  layout "admin"
  # GET /events
  # GET /events.json
  def index
    @events = Event.order('scheduled_on DESC').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { 
          redirect_to events_path
          gflash success: 'Event was successfully created.' 
        }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { 
          redirect_to events_path
          gflash success: 'Event was successfully updated.' 
        }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= nested_form_for @event, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <div class="span8">
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :poster, "#{@event.persisted? ? 'Change poster' : 'Poster' }", :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :poster, :class => 'text_field' %>
      </div>
    </div>  
    <div class="control-group">
      <%= f.label :thumbnail_poster, "#{@event.persisted? ? 'Change poster thmbnail' : 'Poster thmbnail' }", :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :thumbnail_poster, :class => 'text_field' %>
      </div>
    </div>  
    <div class="control-group">
      <%= f.label :scheduled_on, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :scheduled_on, :value => (@event.scheduled_on.strftime("%d %B, %Y") rescue ""), :class => 'text_field datepicker' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :class => 'text_area', :size => "50x8", :style => "width:auto" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :youtube_url, "Youtube Embed Code (Keep the width less than 500px)", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :youtube_url, :class => 'text_area', :size => "50x8", :style => "width:auto" %>
      </div>
    </div>
  </div>
  <div class="span3">
    <% unless @event.poster.blank? %>
      Event Poster <br>
      <%= image_tag @event.poster.url, :width => 270 %>
    <% end %>
    <br><br>
    <% unless @event.thumbnail_poster.blank? %>
      Event Poster thumbnail<br>
      <%= image_tag @event.thumbnail_poster.url(:cropped), :width => 270 %>
    <% end %>
  </div>
  <div class="clearfix"></div>
<!--   <%= f.fields_for :event_pictures do |event_picture| %>
    <div class="clearfix">
      <h4>Event Media</h4>
      <hr>
      <div class="pull-left">
        <div class="control-group">
          <%= event_picture.label :image, event_picture.object.persisted? ? "Change image" : "Image", :class => 'control-label' %>
          <div class="controls">      
            <%= event_picture.file_field :image, :class => 'file_field' %>
          </div>
        </div>
        <div class="control-group">
          <span style="padding-left:75px"></span><%= event_picture.link_to_remove "Remove this menu page" %>
        </div>
      </div>
      <div class="pull-left" style="padding-left: 50px">
        <% if event_picture.object.persisted? %>
          <%= link_to image_tag(event_picture.object.image.url(:thumb)), event_picture.object.image.url, :target => "_blank" %>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= f.link_to_add "Add event media", :event_pictures %> -->

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-success' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Edit #{model_class.model_name.human}", :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1>
    <%= t '.title', :default => model_class.model_name.human.pluralize %>
    <%= link_to new_event_path, :class => 'btn btn-success pull-right' do %>
      <i class='icon-plus icon-white'></i> Add Event
    <% end %>
  </h1>
</div>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th style="">Poster</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:scheduled_on) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= image_tag event.thumbnail_poster.url(:cropped), :size => "100x100" %></td>
        <td><%= event.name %></td>
        <td><%= event.scheduled_on.strftime("%d %B, %Y") rescue "" %></td>
        <td style="width:400px"><%= truncate(event.description, length: 160) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => "New #{model_class.model_name.human}", :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @event.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:scheduled_on) %>:</strong></dt>
  <dd><%= @event.scheduled_on %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @event.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:done) %>:</strong></dt>
  <dd><%= @event.done %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              events_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_path(@event), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_path(@event),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>