config/routes.rb
Cheval::Application.routes.draw do
  resources :twitter_tags


  resources :food_sliders


devise_for :admins, :controllers => {:registrations => "registrations"}, :skip => [:registrations]
as :admin do
  get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
  put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
end

  match "/about" => "static#about", as: :about
  match "/menu" => "static#menu", as: :menu
  match "/photos" => "static#photos", as: :photos
  match "/art_club" => "static#art_club", as: :art_club
  match "/press" => "static#press", as: :press
  match "/contact" => "static#contact", as: :contact
  match "/upcoming_events" => "static#upcoming_events", as: :upcoming_events
  match "/past_events" => "static#past_events", as: :past_events
  match "/show_event/:id" => "static#show_event", as: :show_event

  scope "/admin" do
    root to: "events#index"
    resources :events
    resources :slider_images  
    resources :special_menus
    resources :press_links
    resources :print_media
  end

  root to: "static#index"
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_pictures
  attr_accessible :description, :done, :name, :scheduled_on, :poster, :event_pictures_attributes, :thumbnail_poster, :youtube_url
  has_attached_file :poster, :default_url => "/assets/missing.png"
  has_attached_file :thumbnail_poster, :styles => { :cropped => "270x270!" }, :default_url => "/assets/missing.png"
  # default_scope order("created_at DESC")
  scope :upcoming, lambda { where("scheduled_on >= ?", (Date.today-1.days)).order("scheduled_on ASC") }
  scope :past, lambda { where("scheduled_on < ?", (Date.today-1.days)).order("scheduled_on DESC") }
  validates_presence_of :name, :scheduled_on, :poster, :description
  accepts_nested_attributes_for :event_pictures, :allow_destroy => true
end

app/models/event_picture.rb
class EventPicture < ActiveRecord::Base
  belongs_to :event
  has_attached_file :image, :styles => { :thumb => "100x100#", }, :default_url => "/images/:style/missing.png"  
  attr_accessible :image
end

app/models/food_slider.rb
class FoodSlider < ActiveRecord::Base
  attr_accessible :hidden, :image
  has_attached_file :image, :styles => { :thumb => "300x100!", :cropped => "1200x500#" }, :default_url => "/images/:style/missing.png"
end

app/models/menu_image.rb
class MenuImage < ActiveRecord::Base
  belongs_to :special_menu
  attr_accessible :page_number, :image, :page_number
  has_attached_file :image, :styles => { :thumb => "100x140!", :cropped => "507x700!" }, :default_url => "/images/:style/missing.png"  
  default_scope order("page_number ASC")
end

app/models/press_link.rb
class PressLink < ActiveRecord::Base
  attr_accessible :description, :url, :image
  has_attached_file :image, :styles => { :thumb => "120x120#" }, :default_url => "/images/:style/missing.png"  
  default_scope order("created_at DESC")
end

app/models/print_medium.rb
class PrintMedium < ActiveRecord::Base
  attr_accessible :hidden, :image
  has_attached_file :image, :styles => { :thumb => "100x140!", :cropped => "507x700!" }, :default_url => "/images/:style/missing.png"  
end

app/models/slider_image.rb
class SliderImage < ActiveRecord::Base
  attr_accessible :hidden, :image
  has_attached_file :image, :styles => { :thumb => "300x100!", :cropped => "1200x400!" }, :default_url => "/images/:style/missing.png"
end

app/models/special_menu.rb
class SpecialMenu < ActiveRecord::Base
  attr_accessible :description, :name, :menu_images_attributes, :hidden, :thumbnail_image
  has_many :menu_images
  has_attached_file :thumbnail_image, :styles => { :cropped => "270x270!" }, :default_url => "/assets/missing.png"
  accepts_nested_attributes_for :menu_images, :allow_destroy => true
  default_scope where("hidden = false").order("created_at DESC")
end

app/models/testimony.rb
class Testimony < ActiveRecord::Base
  attr_accessible :content, :screen_name, :tweet_id

  def self.pull_tweets
  hashtags = (TwitterTag.where(:active => true).map{|t| "#" + t.tag }.join(" OR ") + " OR @chevalmumbai")

  Twitter.search(hashtags, :count => 10, :result_type => "recent").results.each do |tweet|
    unless exists?(tweet_id: tweet.id)
      create!(
        tweet_id: tweet.id,
        content: tweet.text,
        screen_name: tweet.user.screen_name,
      )
    end
  end
end
end

app/models/twitter_tag.rb
class TwitterTag < ActiveRecord::Base
  attr_accessible :active, :tag
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_admin!
  layout "admin"
  # GET /events
  # GET /events.json
  def index
    @events = Event.order('scheduled_on DESC').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { 
          redirect_to events_path
          gflash success: 'Event was successfully created.' 
        }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { 
          redirect_to events_path
          gflash success: 'Event was successfully updated.' 
        }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/food_sliders_helper.rb
module FoodSlidersHelper
end

app/helpers/press_links_helper.rb
module PressLinksHelper
end

app/helpers/slider_images_helper.rb
module SliderImagesHelper
end

app/helpers/special_menus_helper.rb
module SpecialMenusHelper
end

app/helpers/twitter_tags_helper.rb
module TwitterTagsHelper
end

app/helpers/unsorted_helper.rb
module UnsortedHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Cheval" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "admin", :media => "all" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

  </head>
  <body>
    <div class="wrap">
      <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <a class="brand" href="<%= root_path %>">Cheval</a>
            <div class="container nav-collapse">
              <ul class="nav">
                <li><%= link_to "Events", events_path %></li>
                <li><%= link_to "Home Slider", slider_images_path %></li>
                <li><%= link_to "Bar Slider", food_sliders_path %></li>
                <li><%= link_to "Special Menus", special_menus_path %></li>
                <li><%= link_to "Press Links", press_links_path %></li>
                <li><%= link_to "Twitter Tags", twitter_tags_path %></li>
                <li><%= link_to "Print Media", print_media_path %></li>
              </ul>
              <ul class="pull-right nav">
                <% if admin_signed_in? %>
                  <li class="dropdown">
                      <%= link_to current_admin.email, "javascript:void(0)", :method => :delete, "data-toggle" => "dropdown", :class => "dropdown-toggle" %>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                        <li><%= link_to "Settings", edit_admin_registration_path %></li>
                        <li><%= link_to "Logout", destroy_admin_session_path, :method => :delete %></li>
                      </ul>
                    </li>
                <% end %>
                
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>

      <div class="clearfix"></div>
      <div class="container main">
        <div class="row">
          <div class="span12">
            <%= yield %>
          </div>
        </div>
      </div>
      <div id="push"></div>
    </div>
    <div id="footer">
      
    </div>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= js extend_gritter :position => :bottom_left %>
    <%= tinymce %>
    <script type="text/javascript">
      <% if notice %>
        <%= add_gritter(notice, :image => :success, :title => "Success!!!") %>
      <% end %>
      <% if alert %>
        <%= add_gritter(alert, :image => :error, :title => "Oops!!!") %>
      <% end %>
    </script>
    <%= gflash %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Cheval Mumbai</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>
  <%= gflash %>
  <!--[if lt IE 7]>
      <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
  <![endif]-->
  <div class="outer_container">
    <div class="center_content">
      <div class="header">
        <a class="logo" href="<%= root_path %>"></a>
        <div class="top_nav">
          <ul>
            <li><a href="<%= root_path %>" class="<%='active' if params[:action] == 'index' %>">Home</a></li>
            <li><a href="<%= about_path %>" class="<%='active' if params[:action] == 'about'%>">About Us</a></li>
            <li><a href="<%= menu_path %>" class="<%='active' if params[:action] == 'menu'%>">Menus</a></li>
            <li><a href="<%= photos_path %>" class="<%='active' if params[:action] == 'photos'%>">Food and Bar Gallery</a></li>
            <li><a href="<%= art_club_path %>" class="<%='active' if params[:action] == 'art_club'%>">Cheval Art Club</a></li>
            <li><a href="<%= press_path %>" class="<%= params[:action] == 'press'%>">Press</a></li>
            <li><a href="<%= contact_path %>" class="<%='active' if params[:action] == 'contact'%>">Contact</a></li>
          </ul>
        </div>
      </div>        
      <div class="clear"></div>
      <%= yield %>
    </div>
    <div class="clear"></div>
  </div>
  <div class="clear"></div>
  <div class="footer">
    <a href="<%= contact_path %>">Contact Us</a>
    <span class="copyright_info"></span>
  </div>
</body>
</html>